let settings = {
  discus: {
    vz: -1000,
    vy: -1000,
    pitch: 45,
    dt: 0.001,
    plotScale: 0.1,
    color: "white",
  },
  control: {
    orbit: true,
    simulate: false,
    debug: false,
    sensitivityZoom: 0.05,
    fps: 60,
    followDiscus: true,
    renderDistance: 5,
  },
  events: {
    reload: false,
    homeCamera: false,
    toggleDebug: false,
    tpToDiscus: false,
    variableChanges: {
      control: {},
      discus: {},
    },
  },
  menu: {
    widgets: [
      {
        type: "slider",
        location: "discus",
        target: "vz",
        minValue: -10000,
        maxValue: 10000,
        step: 1,
      },
      {
        type: "inputField",
        location: "discus",
        target: "vz",
      },
      {
        type: "slider",
        location: "discus",
        target: "vy",
        minValue: -10000,
        maxValue: 10000,
        step: 1,
      },
      {
        type: "inputField",
        location: "discus",
        target: "vy",
      },
      {
        type: "slider",
        location: "discus",
        target: "dt",
        minValue: 0.001,
        maxValue: 1.00,
        step: 0.001,
      },
      {
        type: "inputField",
        location: "discus",
        target: "dt",
      },
      {
        type: "slider",
        location: "discus",
        target: "pitch",
        minValue: 0,
        maxValue: 90,
        step: 1,
      },
      {
        type: "inputField",
        location: "discus",
        target: "pitch",
      },
      {
        type: "slider",
        location: "discus",
        target: "plotScale",
        minValue: 0.01,
        maxValue: 1,
        step: 0.01,
      },
      {
        type: "inputField",
        location: "discus",
        target: "plotScale",
      },
      {
        type: "button",
        location: "events",
        target: "toggleDebug",
      },
      {
        type: "button",
        location: "events",
        target: "tpToDiscus",
      },
      {
        type: "button",
        location: "events",
        target: "homeCamera",
      },
      {
        type: "checkbox",
        location: "control",
        target: "simulate",
      },
      {
        type: "button",
        location: "events",
        target: "reload",
      },
      {
        type: "checkbox",
        location: "control",
        target: "followDiscus",
      },
    ],
  },
};
